spectrometer:
  serial_number: "SERIALNUMBERHERE"

acquisition:
  integration_time_us: 10000
  scans_to_average: 20
  runs_to_make: 1
  notes: "MachZehnInteMeasurement"

Analysis:
  GaussianSmoothing: 2
  HampelSmoothing: 2